spring.application.name=jobportal
spring.mvc.apiversion.use.header=Api-Version

# DATABASE CONFIGURATION
#spring.datasource.url=jdbc:h2:mem:jobportaldb
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
spring.datasource.url=jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:jobportal}
spring.datasource.username = ${DATABASE_USERNAME:root}
spring.datasource.password=  ${DATABASE_PASSWORD:root}


#for mySQL


# H2 CONSOLE CONFIGURATION
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JPA / HIBERNATE CONFIGURATION
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=${SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Ensures schema/data scripts run on startup.
spring.sql.init.mode=embedded

spring.sql.init.schema-locations=optional:classpath:sql/schema.sql
spring.sql.init.data-locations=optional:classpath:sql/data.sql

# LOGGING CONFIGURATION

logging.pattern.console=${CONSOLE_LOG_PATTERN:%white(%d{HH:mm:ss.SSS}) %yellow(%-5level) %blue([%thread]) %red(%logger{15}) - %green(%msg%n)}